---
- name: restart bind
  service:
    name: "{{ bind_consul_bind_daemon }}"
    state: restarted
  become: true

- name: save iptables v4 rules
  shell: iptables-save > /etc/iptables/rules.v4
  listen: save iptables
  become: true

- name: save iptables v6 rules
  shell: ip6tables-save > /etc/iptables/rules.v6
  listen: save iptables
  become: true
